config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'discover' => 'static_pages#discover'
  get 'about' => 'static_pages#about'
  get 'feedpro' => 'static_pages#feedpro'
  get 'feedone' => 'static_pages#feedone'
  get 'feedimg' => 'static_pages#feedimg'
  get 'setting' => 'static_pages#setting'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'invite' => 'users#invite'

  resources :fightposts do
    resources :comments, only: [:create, :destroy]
    resources :likers, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resource :profile
  get 'tags/:tag', to: 'static_pages#home', as: :tag

  resources :users, path: '', as: 'users' do
    member do
      get :fightposts
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if user_signed_in?
      if params[:tag]
        @feed_items = current_user.feed.tagged_with(params[:tag]).paginate(page: params[:page])
      else
        @feed_items = current_user.feed.paginate(page: params[:page])
      end
    end
  end

  def discover
  end

  def setting
  end

  def about
  end

  def feedpro
    # 暂时的页面
  end

  def feedone
  end

  def feedimg
  end
end

app/views/static_pages/_welcome.html.erb
<% provide(:title, "Home") %>

<div class="row home">
	<div class="col-md-12 slogan">
		<h1><strong>Fighting Technology Group Hub</strong></h1>
		<h4>在这里汇聚着一群普通的格斗技术爱好者</h4>
		<h5>在这里有练习太极、八卦、形意拳、拳击、空手道、跆拳道、柔道、剑道...等中外武者</h5>
		<h4>在这里可以记录下你在格斗道路上的点滴</h4>
		<h4>在这里通过分享、交流获得更多的乐趣</h4>
		<h4>欢迎来到Fighting Technology Group Hub</h4>
	</div>

	<div class="col-md-6 col-md-offset-3 photo">
		<ul class="list-inline">
			<li data-toggle="tooltip" data-placement="left" title="修练功夫的目的不是致力于击破石块或木板，我们更关心的是用它影响我们的整个思想和生活方式。"><%= image_tag("index-9", size: "200") %></li>
			<li><%= image_tag("index-10a", size: "200") %></li>
		</ul>
	</div>
	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-2", size: "200") %></li>
			<li><%= image_tag("index-5", size: "200") %></li>
			<li><%= image_tag("index-13", size: "200") %></li>
			<li><%= image_tag("index-12a", size: "200") %></li>
		</ul>
	</div>
	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-4", size: "200") %></li>
			<li><%= image_tag("index-14", size: "200") %></li>
			<li>
				<blockquote>
				  <p>修练功夫的目的不是致力于击破石块或木板，我们更关心的是用它影响我们的整个思想和生活方式。</p>
				</blockquote>
			</li>
		</ul>
	</div>

	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-6", size: "200") %></li>
			<li><%= image_tag("index-8a", size: "200") %></li>
			<li><%= image_tag("index-5", size: "200") %></li>
			<li><%= image_tag("index-1", size: "200") %></li>
		</ul>
	</div>

	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-11", size: "200") %></li>
			<li>
				<blockquote>
				  <p>让我们通过格斗运动获得健康和乐趣</p>
				</blockquote>
			</li>
			<li><%= image_tag("index-7a", size: "200") %></li>
		</ul>
	</div>

	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-8", size: "200") %></li>
			<li><%= image_tag("index-6a", size: "200") %></li>
			<li><%= image_tag("index-2", size: "200") %></li>
			<li><%= image_tag("index-4", size: "200") %></li>
		</ul>
	</div>
	
	<hr>

</div>

<script>
	
	$(function () {
	  $('[data-toggle="tooltip"]').tooltip()
	})
</script>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/discover.html.erb
<% provide(:title, 'descover') %>
<div class="row common-header">
  <div class="col-md-12">
  	<input type="text" class="form-control input-sm search" placeholder="search">
  </div>
</div>

<div class="row topic">
	<div class="col-md-12">
		<div class="row">
		  <div class="col-xs-6 topic-box">
		  	<i class="fa fa-fire fa-2x"></i>
		  	<p><small><%= link_to "热门作品", '#' %></small></p>
		  </div>
		  <div class="col-xs-6 topic-box">
		  	<i class="fa fa-thumbs-o-up fa-2x"></i>
		  	<p><small><%= link_to "高手榜", '#' %></small></p>
		  </div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="row">
		  <div class="col-xs-6 topic-box">
				<i class="fa fa-crosshairs fa-2x"></i>
		  	<p><small><%= link_to "最新作品", '#' %></small></p>
		  </div>
		  <div class="col-xs-6 topic-box">
		  	<i class="fa fa-tags fa-2x"></i>
		  	<p><small><%= link_to "所有标签", '#' %></small></p>
		  </div>
		</div>
	</div>
	<p class="trending-tags"><small>热门标签</small></p>
</div>

<div class="row tag-list tag-1">
  <div class="col-xs-12 tag">
  	<p>太极拳</p>
  </div>
</div>

<div class="row tag-list tag-2">
  <div class="col-xs-12 tag">
  	<p>跆拳道</p>
  </div>
</div>

<div class="row tag-list tag-3">
  <div class="col-xs-12 tag">
  	<p>空手道</p>
  </div>
</div>

<div class="row tag-list tag-4">
  <div class="col-xs-12 tag">
  	<p>马伽术</p>
  </div>
</div>

<div class="row tag-list tag-5">
  <div class="col-xs-12 tag">
  	<p>合气道</p>
  </div>
</div>

app/views/static_pages/feedimg.html.erb
<div class="row figth-body">
	<div class="container">
	  <div class="col-md-8">
			<div class="fight-img">
				<%= image_tag 'sanda', height: '420' %>
			</div>
	  	<div class="fight-user">
				<div class="media">
				  <div class="media-left">
				    <a href="#">
				      <%= image_tag "index-1a", size: '80', class: "avatar" %>
				    </a>
				    <h5>Shin Zhang</h5>
				    <%= button_tag(type: 'submit', class: "btn btn-xs btn-info") do %>
						  <%= fa_icon "plus", text: "Follow" %>
						<% end %>
				  </div>
				  <div class="media-body">
						<p>Aikido Demonstration by Bruno Gonzalez's Team at SportAccord World Combat Games 2013. With Bruno Gonzalez, 5th Dan, Henriette Flader, 2nd Dan, Hélène Doué, 4th Dan and Fabrice Croizé, 4th Dan, from France. Footage courtesy of IES in Sports and SportAccord.</p>

						<span class="social-action">
				      <ul class="list-inline">
				        <li><i class="fa fa-heart"></i>289</li>
				        <li><%= fa_icon "comment" %><%= 208 -%></li>
				        <li><i class="fa fa-share-square-o"></i></li>
				      </ul>
				    </span>
				  </div>
				</div>
	  	</div>

	  	<div class="figth-comment">
	  		<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<textarea class="form-control" rows="3"></textarea>
				  	<%= button 'Comment', context: :info %>
				  </div>
				</div>
	  	</div>

	  	<div class="figth-comment">
	  		<h4>21 Comment</h4>
	  		<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
				<hr>
				<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
				<hr>
				<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
				<hr>
				<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
	  	</div>
	  </div>
	  <div class="col-md-4">
	  	<div class="figth-recommend">
	  		<h4>推荐</h4>
				<div class="row">
	  			<div class="col-md-12">
	  				<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>

						<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>

						<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>

						<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>
	  			</div>
				</div>
	  	</div>
	  </div>
	</div>
</div>

app/views/static_pages/feedone.html.erb
<div class="row figth-content">
  <div class="col-md-12 figth-video">
  	<div class="row">
		  <div class="col-md-6 col-md-offset-3">
		  	<div class="embed-responsive embed-responsive-16by9">
				  <iframe src="https://www.youtube.com/embed/1C-6BdvRkbw" frameborder="0" allowfullscreen></iframe>
				</div>
		  </div>
		</div>
  </div>
</div>

<div class="row figth-body">
	<div class="container">
	  <div class="col-md-8">
	  	<div class="fight-user">
				<div class="media">
				  <div class="media-left">
				    <a href="#">
				      <%= image_tag "index-1a", size: '80', class: "avatar" %>
				    </a>
				    <h5>Shin Zhang</h5>
				    <%= button_tag(type: 'submit', class: "btn btn-xs btn-info") do %>
						  <%= fa_icon "plus", text: "Follow" %>
						<% end %>
				  </div>
				  <div class="media-body">
						<p>Aikido Demonstration by Bruno Gonzalez's Team at SportAccord World Combat Games 2013. With Bruno Gonzalez, 5th Dan, Henriette Flader, 2nd Dan, Hélène Doué, 4th Dan and Fabrice Croizé, 4th Dan, from France. Footage courtesy of IES in Sports and SportAccord.</p>

						<span class="social-action">
				      <ul class="list-inline">
				        <li><i class="fa fa-heart"></i>289</li>
				        <li><%= fa_icon "comment" %><%= 208 -%></li>
				        <li><i class="fa fa-share-square-o"></i></li>
				      </ul>
				    </span>
				  </div>
				</div>
	  	</div>

	  	<div class="figth-comment">
	  		<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<textarea class="form-control" rows="3"></textarea>
				  	<%= button 'Comment', context: :info %>
				  </div>
				</div>
	  	</div>

	  	<div class="figth-comment">
	  		<h4>21 Comment</h4>
	  		<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
				<hr>
				<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
				<hr>
				<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
				<hr>
				<div class="row">
	  			<div class="col-md-1">
	  				<%= link_to image_tag "logo-2.png", size: "32", class: "img-circle avatar" %>
	  			</div>
				  <div class="col-md-11">
				  	<h5>Michael Pykh</h5>
				  	<p>Henriette Flader, 2nd Dan, Hélène Doué,</p>
				  	<small>2016年3月7日</small>
				  </div>
				</div>
	  	</div>
	  </div>
	  <div class="col-md-4">
	  	<div class="figth-recommend">
	  		<h4>推荐</h4>
				<div class="row">
	  			<div class="col-md-12">
	  				<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>

						<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>

						<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>

						<div class="media">
						  <div class="media-left">
						    <%= link_to image_tag "feed", height: '60' %>
						  </div>
						  <div class="media-body">
						  	<small>Henriette Flader, 2nd Dan, Hélène Doué,</small>
						    <h6 class="media-heading">Media heading</h6>
						  </div>
						</div>
	  			</div>
				</div>
	  	</div>
	  </div>
	</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="row common-header">
  <div class="col-md-12">
  	<ul class="list-inline">
		  <li>
		  	<div class="sort-box active">
			  	推荐
			  </div>
		  </li>
		  <li>
		  	<div class="sort-box">
			  	关注
			  </div>
		  </li>
		</ul>
  </div>
</div>
<div class="row home">
	<%= render 'shared/feed' %>
</div>


<%#= link_to (fa_icon "download", text: "下载App"), new_fightpost_path, class: "btn btn-sm btn-info" %>
<%# tag_cloud Fightpost.tag_counts, %w[s m l] do |tag, css_class| %>
	<%#= link_to tag.name, tag_path(tag.name), class: css_class %>
<%# end %>

app/views/static_pages/homepro.html.erb
<% provide(:title, "Home") %>

<div class="row home">
	<div class="col-md-12 slogan">
		<h1><strong>Fighting Technology Group Hub</strong></h1>
		<h4>在这里汇聚着一群普通的格斗技术爱好者</h4>
		<h5>在这里有练习太极、八卦、形意拳、拳击、空手道、跆拳道、柔道、剑道...等中外武者</h5>
		<h4>在这里可以记录下你在格斗道路上的点滴</h4>
		<h4>在这里通过分享、交流获得更多的乐趣</h4>
		<h4>欢迎来到Fighting Technology Group Hub</h4>
	</div>

	<div class="col-md-12 logo">
		<%= image_tag "logo", size: "66" %>
	</div>

	<div class="col-md-6 col-md-offset-3 photo">
		<ul class="list-inline">
			<li data-toggle="tooltip" data-placement="left" title="修练功夫的目的不是致力于击破石块或木板，我们更关心的是用它影响我们的整个思想和生活方式。"><%= image_tag("index-9", size: "200") %></li>
			<li><%= image_tag("index-10a", size: "200") %></li>
		</ul>
	</div>
	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-2", size: "200") %></li>
			<li><%= image_tag("index-5", size: "200") %></li>
			<li><%= image_tag("index-13", size: "200") %></li>
			<li><%= image_tag("index-12a", size: "200") %></li>
		</ul>
	</div>
	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-4", size: "200") %></li>
			<li><%= image_tag("index-14", size: "200") %></li>
			<li>
				<blockquote>
				  <p>修练功夫的目的不是致力于击破石块或木板，我们更关心的是用它影响我们的整个思想和生活方式。</p>
				</blockquote>
			</li>
		</ul>
	</div>

	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-6", size: "200") %></li>
			<li><%= image_tag("index-8a", size: "200") %></li>
			<li><%= image_tag("index-5", size: "200") %></li>
			<li><%= image_tag("index-1", size: "200") %></li>
		</ul>
	</div>

	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-11", size: "200") %></li>
			<li>
				<blockquote>
				  <p>让我们通过格斗运动获得健康和乐趣</p>
				</blockquote>
			</li>
			<li><%= image_tag("index-7a", size: "200") %></li>
		</ul>
	</div>

	<div class="col-md-10 col-md-offset-1 photo">
		<ul class="list-inline">
			<li><%= image_tag("index-8", size: "200") %></li>
			<li><%= image_tag("index-6a", size: "200") %></li>
			<li><%= image_tag("index-2", size: "200") %></li>
			<li><%= image_tag("index-4", size: "200") %></li>
		</ul>
	</div>
	
	<hr>

</div>

<script>
	
	$(function () {
	  $('[data-toggle="tooltip"]').tooltip()
	})
</script>

app/views/static_pages/setting.html.erb
<% provide(:title, 'setting') %>

<div class="row common-header">
  <div class="col-xs-1">
     <%= link_to (fa_icon "angle-left"), '#', class: "fa-2x" %>
  </div>
  <div class="col-xs-10">
    <p>setting</p>
  </div>
</div>


<table class="table table-striped common-list setting-table">
  <tr>
  	<td><p>关注FTG公众号</p></td>
  </tr>
  <tr>
    <td><p>关注FTG微博号</p></td>
  </tr>
  <tr>
    <td><p>获得FTG礼品</p></td>
  </tr>
  <tr>
    <td><p>给我们评价</p></td>
  </tr>
  <tr>
    <td><p>给我们建议</p></td>
  </tr>
</table>


<table class="table table-striped common-list setting-table setting-other">
  <tr>
    <td><p>设置提醒</p></td>
    <td class="angle-right"><%= link_to (fa_icon "angle-right"), '#' %></td>
  </tr>
  <tr>
    <td><p>管理黑名单</p></td>
    <td class="angle-right"><%= link_to (fa_icon "angle-right"), '#' %></td>
  </tr>
  <tr>
    <td><p>设置隐私</p></td>
    <td class="angle-right"><%= link_to (fa_icon "angle-right"), '#' %></td>
  </tr>
</table>

<table class="table table-striped common-list setting-table setting-other">
  <tr>
    <td><p>使用条款</p></td>
    <td class="angle-right"><%= link_to (fa_icon "angle-right"), '#' %></td>
  </tr>
  <tr>
    <td><p>隐私条款</p></td>
    <td class="angle-right"><%= link_to (fa_icon "angle-right"), '#' %></td>
  </tr>
  <tr>
    <td><p>版权声明</p></td>
    <td class="angle-right"><%= link_to (fa_icon "angle-right"), '#' %></td>
  </tr>
</table>

<table class="table table-striped common-list setting-table">
  <tr>
    <td><p>清空缓存</p></td>
  </tr>
  <tr>
    <td><p>退出账号</p></td>
  </tr>
  <tr>
    <td><p>删除账号</p></td>
  </tr>
</table>