config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'discover' => 'static_pages#discover'
  get 'about' => 'static_pages#about'
  get 'feedpro' => 'static_pages#feedpro'
  get 'feedone' => 'static_pages#feedone'
  get 'feedimg' => 'static_pages#feedimg'
  get 'setting' => 'static_pages#setting'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'invite' => 'users#invite'

  resources :fightposts do
    resources :comments, only: [:create, :destroy]
    resources :likers, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resource :profile
  get 'tags/:tag', to: 'static_pages#home', as: :tag

  resources :users, path: '', as: 'users' do
    member do
      get :fightposts
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, on: :create, message: "can't be blank"
  has_many :fightposts, dependent: :destroy
  has_many :active_relationships,  class_name:  'Relationship',
                                   foreign_key: 'follower_id',
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent:   :destroy

  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :likers, dependent: :destroy

  def feed
    Fightpost.where(user: self).or(Fightpost.where(user: following))
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :ensure_is_admin, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @fightposts = @user.fightposts.paginate(page: params[:page])
    @profile = @user.profile
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  def invite
    
  end

  def following
    @title = 'Following'
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def ensure_is_admin
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= button_tag(type: 'submit', class: "btn btn-sm btn-info") do %>
	   <%= fa_icon "plus", text: "Follow" %>
	<% end %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= button_tag(type: 'submit', class: "btn btn-sm") do %>
	   <%= fa_icon "times", text: "Unfollow" %>
	<% end %>
<% end %>

app/views/users/_user.html.erb
<tr>
	<td><%= image_tag("shin-avatar", size: "40", class: "img-circle avatar") %></td>
	<td>
		<p class="username"><%= link_to user.name, user %>
			<% if current_user.admin? && !current_user?(user) %>
	    | <%= link_to "delete", user, method: :delete,
	                                  data: { confirm: "You sure?" } %>
	    <% end %>
		</p>
		<small>合气道，太极拳</small>
	</td>
	<td>
		<button class="btn btn-danger btn-sm" type="submit"><i class="fa fa fa-user-times"></i></button>
	</td>
</tr>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div class="row common-header">
  <div class="col-xs-1">
     <%= link_to (fa_icon "angle-left"), discover_path, class: "fa-2x" %>
  </div>
  <div class="col-xs-10">
    <p>所有用户</p>
  </div>
</div>

<table class="table common-list">
  <%# if @users.admin? %>
    <%= render @users %>
  <%# end %>
</table>

<div class="row">
  <div class="col-xs-12">
    <%= will_paginate @users, :page_links => false, class: 'pagination-sm' %>
  </div>
</div>

app/views/users/invite.html.erb
<% provide(:title, 'invite') %>

<div class="row common-header">
  <div class="col-xs-1">
     <%= link_to (fa_icon "angle-left"), user_path(current_user), class: "fa-2x" %>
  </div>
  <div class="col-xs-10">
    <p>invite</p>
  </div>
</div>

<div class="row common-header invite-header">
  <div class="col-md-12">
    <input type="text" class="form-control input-sm search" placeholder="search">
  </div>
</div>


<div class="row invite-weixin">
  <div class="col-xs-1 left">
  	<%= link_to (fa_icon "weixin"), '#', class: "weixin-icon" %>
  </div>
  <div class="col-xs-8 center"><p>invite to weichat</p></div>
  <div class="col-xs-1 right">
  	<%= link_to (fa_icon "angle-right"), '#', class: "fa-2x angle-right" %>
  </div>
</div>

<table class="table common-list">
  <tr>
  	<td><%= image_tag("shin-avatar", size: "40", class: "img-circle avatar") %></td>
  	<td>
  		<p class="username">Kristen Hancher</p>
  		<small>合气道，太极拳</small>
  	</td>
  	<td>
  		<button class="btn btn-success btn-sm" type="submit"><i class="fa fa-user-plus"></i></button>
  	</td>
  </tr>
  <tr>
  	<td><%= image_tag("shin-avatar", size: "40", class: "img-circle avatar") %></td>
  	<td>
  		<p class="username">Kristen Hancher</p>
  		<small>合气道，太极拳</small>
  	</td>
  	<td>
  		<button class="btn btn-success btn-sm" type="submit"><i class="fa fa-user-plus"></i></button>
  	</td>
  </tr>
  <tr>
  	<td><%= image_tag("shin-avatar", size: "40", class: "img-circle avatar") %></td>
  	<td>
  		<p class="username">Kristen Hancher</p>
  		<small>合气道，太极拳</small>
  	</td>
  	<td>
  		<button class="btn btn-success btn-sm" type="submit"><i class="fa fa-user-plus"></i></button>
  	</td>
  </tr>
  <tr>
  	<td><%= image_tag("shin-avatar", size: "40", class: "img-circle avatar") %></td>
  	<td>
  		<p class="username">Kristen Hancher</p>
  		<small>合气道，太极拳</small>
  	</td>
  	<td>
  		<button class="btn btn-success btn-sm" type="submit"><i class="fa fa-user-plus"></i></button>
  	</td>
  </tr>
  <tr>
  	<td><%= image_tag("shin-avatar", size: "40", class: "img-circle avatar") %></td>
  	<td>
  		<p class="username">Kristen Hancher</p>
  		<small>合气道，太极拳</small>
  	</td>
  	<td>
  		<button class="btn btn-success btn-sm" type="submit"><i class="fa fa-user-plus"></i></button>
  	</td>
  </tr>
</table>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="user-show">
  <div class="row user-show-head">
    <div class="col-xs-4 left">
      <%= link_to (fa_icon "user-plus"), invite_path %>
    </div>
    <div class="col-xs-4 center">
      <h5 class="text-center"><%= @user.name %></h5>
    </div>
    <div class="col-xs-4 right">
      <p class="text-right"><i class="fa fa-cog"></i></p>
    </div>
  </div>
  <div class="row user-show-avatar">
    <div class="col-md-12 text-center">
      <%= image_tag("user.jpg", size: "80", alt: @user.name, class: "img-circle avatar" ) %>
      <p><small>@shinplus</small></p>
      <p>
        <small>
          <% if @profile.nil? %>
            暂无个人介绍!
          <% else %>
            <%= @profile.introduction %>
          <% end %>
        </small>
      </p>
    </div>
  </div>
  <div class="row user-show-content">
    <div class="col-md-12 text-center">
      <div class="stats">
        <%= render 'shared/stats' %>
      </div>
      <section class="stats">
        <%= render 'follow_form' if user_signed_in? %>
      </section>

      <% if user_signed_in? && @user == current_user -%>
        <p><%= link_to "edit profile", profile_path, class: 'btn btn-default', role: 'button' -%></p>
      <% end -%>
    </div>
  </div>
  <div class="row user-show-video">
    <div class="col-xs-4">
      <%= image_tag("index2-1") %>
    </div>
    <div class="col-xs-4">
      <%= image_tag("index2-1") %>
    </div>
    <div class="col-xs-4">
      <%= image_tag("index2-1") %>
    </div>
    <div class="col-xs-4">
      <%= image_tag("index2-1") %>
    </div>
    <div class="col-xs-4">
      <%= image_tag("index2-1") %>
    </div>
    <div class="col-xs-4">
      <%= image_tag("index2-1") %>
    </div>
  </div>
</div>





<%# if @user.fightposts.any? %>
  <%#= @user.fightposts.count %>
  <%#= render @fightposts %>
<%# end %>


<!-- <div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%#= image_tag("user.jpg", size: "80", alt: @user.name, class: "avatar" ) %>
        <%#= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%#= render 'shared/stats' %>
    </section>
    <section class="stats">
      <%#= render 'follow_form' if user_signed_in? %>
    </section>
    <section class="stats">
      <%# if @profile.nil? %>
        暂时无资料!
      <%# else %>
        <%#= @profile.introduction %>
      <%# end %>

      <%# if user_signed_in? && @user == current_user -%>
          <p><%#= link_to "Edit Profile", profile_path %></p>
      <%# end -%>
    </section>
  </aside>

  <div class="col-md-8">
    <%# if @user.fightposts.any? %>
      <h3>Fightposts (<%#= @user.fightposts.count %>)</h3>
      <ol class="fightposts">
        <%#= render @fightposts %>
      </ol>
      <%#= will_paginate @fightposts %>
    <%# end %>
  </div>
</div> -->

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row common-header">
  <div class="col-xs-1">
     <%= link_to (fa_icon "angle-left"), '#', class: "fa-2x" %>
  </div>
  <div class="col-xs-10">
    <p>following</p>
  </div>
</div>

<table class="table common-list">
  <% if @users.any? %>
    <%= render @users %>
  <% end %>
</table>

<div class="row">
  <div class="col-xs-12">
    <%= will_paginate @users, :page_links => false, class: 'pagination-sm' %>
  </div>
</div>

<%#= link_to "view my profile", @user %>