config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'discover' => 'static_pages#discover'
  get 'about' => 'static_pages#about'
  get 'feedpro' => 'static_pages#feedpro'
  get 'feedone' => 'static_pages#feedone'
  get 'feedimg' => 'static_pages#feedimg'
  get 'setting' => 'static_pages#setting'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'invite' => 'users#invite'

  resources :fightposts do
    resources :comments, only: [:create, :destroy]
    resources :likers, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resource :profile
  get 'tags/:tag', to: 'static_pages#home', as: :tag

  resources :users, path: '', as: 'users' do
    member do
      get :fightposts
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= flash_class_name(name) %>" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    <%= content_tag :div, msg, :id => "flash_#{name}" %>
		</div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="col-md-5 foot-left">
      <%= image_tag "ftglogo6", height: "40" %>
      <p>在这里汇聚着一群普通的格斗技术爱好者</p>
      <p>在这里有练习太极、八卦、拳击、空手道、跆拳道、剑道...等武者</p>
      <p>在这里可以记录下你在格斗道路上的点滴</p>
      <p>在这里通过分享、交流获得更多的乐趣</p>
      <p>欢迎来到Fighting Technology Group Hub</p>
      <small>
        Copyright © 20015–2016 FTGHUB LLC. All screenshots © their respective owners. 
      </small>
    </div>
    <div class="col-md-4 foot-center">
      <div class="row">
        <div class="col-md-4">
          <ul class="list-unstyled">
            <li><%= link_to "关于FTGHUB",   '#' %></li>
            <li><%= link_to "联系我们", '#' %></li>
            <li><%= link_to "团队", '#' %></li>
            <li><%= link_to "加入我们", '#' %></li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-unstyled">
            <li><%= link_to "广告投放", '#' %></li>
            <li><%= link_to "合作", '#' %></li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-unstyled">
            <li><%= link_to (fa_icon "weixin", text: "微信公众号"), "#", class: "btn btn-sm btn-success" %></li>
            <li><%= link_to "腾讯视频", '#' %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-3 foot-right">
      <small>
        The <a href="http://www.ftghub.com/">FTGHUB</a>
        by <a href="#">Shin Zhang</a> & <a href="#">Eric Guo</a>
      </small>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm">
  <a class="navmenu-brand visible-md visible-lg" href="#">FTGHUB</a>
  <% if user_signed_in? %>
    <% if !current_user.profile.avatar.nil? %>
      <%= image_tag("shin-avatar", size: "36", class: "img-circle ftglogo") %>
      <h5 class="ftglogo"><%= link_to current_user.name, user_path(current_user) %></h5>
    <% else %>
      <li><%= link_to image_tag "logo-2.png", size: "36", class: "img-circle ftglogo" %></li>
      <h5 class="ftglogo"><%= current_user.name %></h5>
    <% end %>
    <hr>
    <ul class="nav navmenu-nav">
      <li><%= link_to (fa_icon "youtube-play", text: "推荐"), root_path %></li>
      <li><%= link_to (fa_icon "search", text: "发现"), discover_path %></li>
      <li><a href="../navmenu-reveal/"><i class="fa fa-star"></i>发布</a></li>
      <li><%= link_to (fa_icon "envelope", text: "消息"), '#' %></li>
      <li><%= link_to (fa_icon "user", text: "个人信息"), user_path(current_user) %></li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
            <%= current_user.name %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t('menu.users'), users_path %></li>
            <li><%= link_to t('menu.notice'), "#" %></li>
            <li><%= link_to t('menu.show'), user_path(current_user) %></li>
            <li><%= link_to t('menu.edit_password'), edit_user_registration_path %></li>
            <li><%= link_to t('menu.logout'), destroy_user_session_path, method: :delete %></li>
            <li><%= link_to t('menu.sign_up'), new_user_registration_path %></li>
            <li><%= link_to t('menu.login'), new_user_session_path %></li>
          </ul>
      </li>
    </ul>
  <% end %>
  <hr>
  <%= image_tag("ftglogo", width: '98', class: "ftglogo" ) %>
</div>

<div class="navbar navbar-default navbar-fixed-top hidden-md hidden-lg">
  <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navmenu">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!--
  ______ _______ _____ _    _ _    _ ____  
 |  ____|__   __/ ____| |  | | |  | |  _ \ 
 | |__     | | | |  __| |__| | |  | | |_) |
 |  __|    | | | | |_ |  __  | |  | |  _ < 
 | |       | | | |__| | |  | | |__| | |_) |
 |_|       |_|  \_____|_|  |_|\____/|____/ 
                                           
 ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
                                ftghub.com                                          
-->

<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/meta' %>
    <title><%= (yield(:title) + ' | ' unless yield(:title).blank?).to_s + 'Fighting Technology Group Hub App' %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/feed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title) + ' | ' unless yield(:title).blank?).to_s + 'Fighting Technology Group Hub App' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>